name: sensors
description: Flutter plugin for accessing the Android and iOS accelerometer and
  gyroscope sensors.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/sensors
<<<<<<< HEAD
version: 0.3.5
=======
version: 0.4.0+1
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f

flutter:
  plugin:
    androidPackage: io.flutter.plugins.sensors
    iosPrefix: FLT
    pluginClass: SensorsPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.3.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
