name: firebase_core
description: Flutter plugin for Firebase Core, enabling connecting to multiple
  Firebase apps.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_core
<<<<<<< HEAD
version: 0.2.5+1
=======
version: 0.3.1+1
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebase.core
    iosPrefix: FLT
    pluginClass: FirebaseCorePlugin

dependencies:
  flutter:
    sdk: flutter
  meta: "^1.0.5"

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
