name: firebase_ml_vision
description: Flutter plugin for Firebase machine learning vision services.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_ml_vision
<<<<<<< HEAD
version: 0.2.1
=======
version: 0.6.0+2
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  image_picker: ^0.4.5
  flutter_test:
    sdk: flutter
  firebase_core: ^0.2.5+1

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebasemlvision
    iosPrefix: FLT
    pluginClass: FirebaseMlVisionPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.2.4 <2.0.0"
