name: firebase_remote_config
description: Flutter plugin for Firebase Remote Config. Update your application look and feel and behaviour without
  re-releasing.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_remote_config
<<<<<<< HEAD
version: 0.0.6+1
=======
version: 0.1.0+2
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^0.2.5+1

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebase.firebaseremoteconfig
    pluginClass: FirebaseRemoteConfigPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
