name: android_alarm_manager
description: Flutter plugin for accessing the Android AlarmManager service, and
  running Dart code in the background when alarms fire.
<<<<<<< HEAD
version: 0.2.3
=======
version: 0.4.1+3
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/android_alarm_manager

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  firebase_auth: ^0.6.6

flutter:
  plugin:
    androidPackage: io.flutter.plugins.androidalarmmanager
    pluginClass: AndroidAlarmManagerPlugin
    iosPrefix: FLT

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
