name: android_intent
description: Flutter plugin for launching Android Intents. Not supported on iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/android_intent
<<<<<<< HEAD
version: 0.2.1
=======
version: 0.3.0+1
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f

flutter:
  plugin:
    androidPackage: io.flutter.plugins.androidintent
    iosPrefix: FLT
    pluginClass: AndroidIntentPlugin

dependencies:
  flutter:
    sdk: flutter
  platform: ^2.0.0
  meta: ^1.0.5

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
