name: google_sign_in
description: Flutter plugin for Google Sign-In, a secure authentication system
  for signing in with a Google account on Android and iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/google_sign_in
<<<<<<< HEAD
version: 3.2.4
=======
version: 4.0.1+1
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f

flutter:
  plugin:
    androidPackage: io.flutter.plugins.googlesignin
    iosPrefix: FLT
    pluginClass: GoogleSignInPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.4

dev_dependencies:
  http: ^0.12.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
