name: battery
description: Flutter plugin for accessing information about the battery state
  (full, charging, discharging) on Android and iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/battery
<<<<<<< HEAD
version: 0.2.3
=======
version: 0.3.0+1
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f

flutter:
  plugin:
    androidPackage: io.flutter.plugins.battery
    iosPrefix: FLT
    pluginClass: BatteryPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

dev_dependencies:
  async: ^2.0.8
  test: ^1.3.0
  mockito: 3.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
