name: firebase_storage_example
description: Demonstrates how to use the firebase_storage plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter
  firebase_storage:
    path: ../
<<<<<<< HEAD
  firebase_core: "^0.2.5+1"
=======
  firebase_core: ^0.3.0
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f
  uuid: "^1.0.0"
  http: ^0.12.0

flutter:
  uses-material-design: true

