name: path_provider
description: Flutter plugin for getting commonly used locations on the Android &
  iOS file systems, such as the temp and app data directories.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/path_provider
<<<<<<< HEAD
version: 0.4.1
=======
version: 0.5.0+1
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f

flutter:
  plugin:
    androidPackage: io.flutter.plugins.pathprovider
    iosPrefix: FLT
    pluginClass: PathProviderPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
