name: quick_actions
description: Flutter plugin for creating shortcuts on home screen, also known as
  Quick Actions on iOS and App Shortcuts on Android.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/quick_actions
<<<<<<< HEAD
version: 0.2.2
=======
version: 0.3.0+1
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f

flutter:
  plugin:
    androidPackage: io.flutter.plugins.quickactions
    iosPrefix: FLT
    pluginClass: QuickActionsPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
