name: android_alarm_manager_example
description: Demonstrates how to use the android_alarm_manager plugin.

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager:
    path: ../
<<<<<<< HEAD
  firebase_auth: ^0.6.6
  google_sign_in: ^3.2.4
=======
  firebase_auth: "^0.8.0+1"
  google_sign_in: "^4.0.0"
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
