name: package_info
description: Flutter plugin for querying information about the application
  package, such as CFBundleVersion on iOS or versionCode on Android.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/package_info
<<<<<<< HEAD
version: 0.3.2+1
=======
version: 0.4.0+1
>>>>>>> 9017d6e7f867af278edd7e8e584d52524f37443f

flutter:
  plugin:
    androidPackage: io.flutter.plugins.packageinfo
    iosPrefix: FLT
    pluginClass: PackageInfoPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
